apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: aws-fleet-cluster
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: XFleetCluster
  resources:
  - name: eks-cluster
    base:
      apiVersion: eks.aws.upbound.io/v1beta1
      kind: Cluster
      spec:
        forProvider:
          region: us-west-2
