apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-fleet-cluster
  labels:
    provider: gcp
spec:
  compositeTypeRef:
    apiVersion: platform.example.org/v1alpha1
    kind: XFleetCluster
  resources:
  - name: gke-cluster
    base:
      apiVersion: container.gcp.upbound.io/v1beta1
      kind: Cluster
      spec:
        forProvider:
          location: us-central1
