apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-demo-microservice
  labels:
    app: demo-microservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo-microservice
  template:
    metadata:
      labels:
        app: demo-microservice
    spec:
      containers:
        - name: demo-microservice
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: CLUSTER_PROVIDER
              value: {{ .Values.env.CLUSTER_PROVIDER | quote }}
