apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}-demo-microservice
  labels:
    app: demo-microservice
    gitops-managed: "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: demo-microservice
  template:
    metadata:
      labels:
        app: demo-microservice
        gitops-managed: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: CLUSTER_PROVIDER
              value: {{ .Values.env.CLUSTER_PROVIDER | quote }}
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
