apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "demo-microservice.fullname" . }}
  labels:
    gitops-managed: "true"
    {{- include "demo-microservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "demo-microservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        gitops-managed: "true"
        {{- include "demo-microservice.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: CLUSTER_PROVIDER
              value: {{ .Values.env.CLUSTER_PROVIDER | quote }}
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
