name: CI
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Build
        working-directory: ./apps/demo-microservice
        run: go build -v ./...
      - name: Helm Lint
        run: helm lint apps/manifests/demo-microservice
