name: YAML Lint
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dependencies
        run: pip install -r requirements.txt
      - name: Lint YAML files
        run: yamllint . -d "{extends: relaxed, rules: {line-length: disable}}"
